### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by ccld** [RafiKueng/paper_models_of_candidates#20]
p1 dark matter has studied > dark matter has been studied  
p2 It’s purpose is twofold. > Its purpose
p3 or groups or that are not in the immediately vicinity  > or groups that are not in the immediately vicinity

**Comment by RafiKueng** [comment]
- [x] p1 dark matter has studied > dark matter has been studied
- [x] p2 It’s purpose is twofold. > Its purpose
- [x] p3 or groups or that are not in the immediately vicinity > or groups that are not in the immediately vicinity

**Comment by RafiKueng** [comment]
thanks alot!!
