### ISSUE TITLE
model selection by volunteers

### ISSUE THREAD

**Issue by RafiKueng** [RafiKueng/paper_models_of_candidates#7]
- [x] choose most recent model by default buut add option to overwrite
- [x] generate images for all models available
- [x] upload all models available
- [ ] ask volunters to override selected model

**Comment by ccld** [comment]
my models available
<table>
<tr><td>SW27	</td><td>ASW0006jh5	</td><td>SDSSJ141432+534004	</td><td>1237661417139012122	213.6372	53.6679		</td><td>http://labs.spacewarps.org/spaghetti/model/GSI5A6JUYX	</td></tr>
<tr><td>SW54	</td><td>ASW0007sez	</td><td>SDSSJ142620+561356	</td><td>1237659326017962463	216.5870	56.2323		</td><td>http://labs.spacewarps.org/spaghetti/model/CCZG2QBCV3	</td></tr>
<tr><td>SW55	</td><td>ASW0007t5y	</td><td>SDSSJ142652.78+560001.3	</td><td>587733424408428946	216.7199	56.0004		</td><td>http://mite.physik.uzh.ch/data/008886	</td></tr>
<tr><td>SW55	</td><td>ASW0007t5y	</td><td>SDSSJ142652.78+560001.3	</td><td>587733424408428946	216.7199	56.0004		</td><td>http://labs.spacewarps.org/spaghetti/model/G7O3HCHKYL	</td></tr>
<tr><td>SW4	</td><td>ASW0009cjs	</td><td>SDSSJ142934.21+562541.0	</td><td>1237659326554964414	217.3925	56.4281		</td><td>http://mite.physik.uzh.ch/data/011763	</td></tr>
<tr><td>SW28	</td><td>ASW0007wfj	</td><td>SDSSJ143055.96+572431.7	</td><td>1237655463776158102	217.7332	57.4088	ASW0007xrs	</td><td>http://mite.physik.uzh.ch/data/008758	</td></tr>
<tr><td>SW5	</td><td>ASW0007k4r	</td><td>SDSSJ143454.47+522850.9	</td><td>1237661387069522357	218.7270	52.4808		</td><td>http://mite.physik.uzh.ch/data/012771	</td></tr>
<tr><td>SW6	</td><td>ASW0008swn	</td><td>SDSSJ143628.00+563833.3	</td><td>1237655368759050812	219.1167	56.6426		</td><td>http://mite.physik.uzh.ch/data/012373	</td></tr>
<tr><td>SW58	</td><td>ASW0007h27	</td><td>SDSSJ143651.59+530706.0	</td><td>1237661388143198984	219.2150	53.1183	ASW0007iwp	</td><td>http://mite.physik.uzh.ch/data/008897	</td></tr>
<tr><td>SW29	</td><td>ASW0008qsm	</td><td>SDSSJ143838+572647	</td><td>1237655369832727187	219.6589	57.4464		</td><td>http://labs.spacewarps.org/spaghetti/model/TQKS2E5S7H	</td></tr>
<tr><td>SW29	</td><td>ASW0008qsm	</td><td>SDSSJ143838+572647	</td><td>1237655369832727187	219.6589	57.4464		</td><td>http://labs.spacewarps.org/spaghetti/model/2SU75GA4XN	</td></tr>
<tr><td>SW7	</td><td>ASW0007e08	</td><td>SDSSJ220256.82+023433.9 	</td><td>1237678619552514623	330.7368	2.5761		</td><td>http://mite.physik.uzh.ch/data/007959	</td></tr>
<tr><td>SW42	</td><td>ASW00096rm	</td><td>SDSSJ221716.58+015826.5	</td><td>1237678597005509292	334.3191	1.9740		</td><td>http://mite.physik.uzh.ch/data/011717	</td></tr>

</table>

**Comment by ccld** [comment]
my models available

<table>
<tr><td>SW19    </td><td>ASW0001ld7 </td><td>SDSSJ020641.97-095156.8    </td><td>1237670955180753231    31.6749 -9.8658     </td><td>http://mite.physik.uzh.ch/data/013397  </td></tr>
<tr><td>SW19    </td><td>ASW0001ld7 </td><td>SDSSJ020642-095157 </td><td>1237670955180753231    31.6750 -9.8658     </td><td>http://labs.spacewarps.org/spaghetti/model/L5TWWXPEJV  </td></tr>
<tr><td>SW43    </td><td>ASW0001c3j </td><td>SDSSJ020810.83-040220.0    </td><td>1237679254670410393    32.0451 -4.0389     </td><td>http://mite.physik.uzh.ch/data/013252  </td></tr>
<tr><td>SW11    </td><td>ASW0002qtn </td><td>SDSSJ020849-050429 </td><td>1237679322323223066    32.2078 -5.0749     </td><td>http://labs.spacewarps.org/spaghetti/model/FFIENOES3L  </td></tr>
<tr><td>SW11    </td><td>ASW0002qtn </td><td>SDSSJ020849.89-050430.0    </td><td>1237669771375214982    32.2079 -5.0750     </td><td>http://mite.physik.uzh.ch/data/013267  </td></tr>
<tr><td>SW20    </td><td>ASW0002dx7 </td><td>SDSSJ021221.15-105251.9    </td><td>1237676673927938137    33.0883 -10.8811        </td><td>http://mite.physik.uzh.ch/data/013274  </td></tr>
<tr><td>SW45    </td><td>ASW00024id </td><td>SDSSJ021225.22-085211.3    </td><td>1237670956255150357    33.1051 -8.8698     </td><td>http://mite.physik.uzh.ch/data/013557  </td></tr>
<tr><td>SW45    </td><td>ASW00024id </td><td>SDSSJ021225.22-085211.3    </td><td>1237670956255150357    33.1051 -8.8698     </td><td>http://labs.spacewarps.org/spaghetti/model/EL3RTBLAWB  </td></tr>
<tr><td>SW46    </td><td>ASW00024q6 </td><td>SDSSJ021317.60-084819.8    </td><td>1237652900762485211    33.3234 -8.8055     </td><td>http://mite.physik.uzh.ch/data/012523  </td></tr>
<tr><td>SW31    </td><td>ASW00021r0 </td><td>SDSSJ021514-092440 </td><td>1237670955718542138    33.8109 -9.4111     </td><td>http://labs.spacewarps.org/spaghetti/model/Y4NEUEI45Y  </td></tr>
<tr><td>SW32    </td><td>ASW0004iye </td><td>SDSSJ022359.89-083651.6    </td><td>1237673701815419155    35.9996 -8.6144     </td><td>http://mite.physik.uzh.ch/data/006709  </td></tr>
<tr><td>SW12    </td><td>ASW0003wsu </td><td>SDSSJ022406.13-062846.5    </td><td>1237679340032360484    36.0260 -6.4806     </td><td>http://mite.physik.uzh.ch/data/012712  </td></tr>
<tr><td>SW12    </td><td>ASW0003wsu </td><td>SDSSJ022406.13-062846.5    </td><td>1237679340032360484    36.0260 -6.4806     </td><td>http://mite.physik.uzh.ch/data/012712  </td></tr>
<tr><td>SW1 </td><td>ASW0004dv8 </td><td>CFHTLS_1166_061401 </td><td>outside SDSS footprint 36.0398 -10.9688        </td><td>http://mite.physik.uzh.ch/data/009951  </td></tr>
<tr><td>SW21    </td><td>ASW0004m3x </td><td>SDSSJ022533-053204 </td><td>1237679440425779462    36.3888 -5.5346     </td><td>http://labs.spacewarps.org/spaghetti/model/QZROE23AUH  </td></tr>
<tr><td>SW22    </td><td>ASW0009ab8 </td><td>CFHTLS_1166_069300 </td><td>outside SDSS footprint 36.8186 -10.9341        </td><td>http://mite.physik.uzh.ch/data/012298  </td></tr>
<tr><td>SW13    </td><td>ASW0009ans </td><td>SDSSJ022805.65-051733.8    </td><td>1237679253061959890    37.0236 -5.2927     </td><td>http://mite.physik.uzh.ch/data/013399  </td></tr>
<tr><td>SW24    </td><td>ASW00050sk </td><td>SDSSJ023315.20-042244.1    </td><td>1237679254136291777    38.3134 -4.3789     </td><td>http://mite.physik.uzh.ch/data/013406  </td></tr>
<tr><td>SW15    </td><td>ASW0004nan </td><td>CFHTLS_1225_187279     </td><td>outside SDSS footprint 132.1708    -4.8772     </td><td>http://mite.physik.uzh.ch/data/013410  </td></tr>
<tr><td>SW25    </td><td>ASW0000717 </td><td>CFHTLS_1217_044109     </td><td>outside SDSS footprint 135.7840    -4.5479 ASW00007mq  </td><td>http://mite.physik.uzh.ch/data/013416  </td></tr>
<tr><td>SW49    </td><td>ASW00007ls </td><td>J090319-040146 </td><td>outside SDSS footprint 135.8311    -4.0297 ASW000066w  </td><td>http://labs.spacewarps.org/spaghetti/model/KEDFRTYJXH  </td></tr>
<tr><td>SW51    </td><td>ASW0006e0o </td><td>SDSSJ135724.86+561614.3    </td><td>1237661388677251308    209.3536    56.2707     </td><td>http://mite.physik.uzh.ch/data/013056  </td></tr>
<tr><td>SW26    </td><td>ASW0005mp6 </td><td>SDSSJ135755.77+571723.2    </td><td>1237659145094628025    209.4820    57.2898 ASW0005ma2  </td><td>http://mite.physik.uzh.ch/data/013339  </td></tr>
<tr><td>SW26    </td><td>ASW0005mp6 </td><td>SDSSJ135755.77+571723.2    </td><td>1237659145094628025    209.4820    57.2898 ASW0005ma2  </td><td>http://labs.spacewarps.org/spaghetti/model/O2IUZZQD7A  </td></tr>
<tr><td>SW16    </td><td>ASW0009bp2 </td><td>SDSSJ140030.21+574437.4    </td><td>1237659326016258178    210.1259    57.7437     </td><td>http://mite.physik.uzh.ch/data/013421  </td></tr>
<tr><td>SW52    </td><td>ASW0006a07 </td><td>SDSSJ140048.66+541102.7    </td><td>1237661386530292302    210.2028    54.1841     </td><td>http://mite.physik.uzh.ch/data/013589  </td></tr>
<tr><td>SW52    </td><td>ASW0006a07 </td><td>SDSSJ140048.66+541102.7    </td><td>1237661386530292302    210.2028    54.1841     </td><td>http://mite.physik.uzh.ch/data/013589  </td></tr>
<tr><td>SW2 </td><td>ASW000619d </td><td>SDSSJ140522.20+574332.9    </td><td>1237659146168697361    211.3425    57.7258     </td><td>http://mite.physik.uzh.ch/data/011421  </td></tr>
<tr><td>SW27    </td><td>ASW0006jh5 </td><td>SDSSJ141432.91+534004.1    </td><td>1237661417139012122    213.6371    53.6678     </td><td>http://mite.physik.uzh.ch/data/013428  </td></tr>
<tr><td>SW27    </td><td>ASW0006jh5 </td><td>SDSSJ141432+534004 </td><td>1237661417139012122    213.6372    53.6679     </td><td>http://labs.spacewarps.org/spaghetti/model/GSI5A6JUYX  </td></tr>
<tr><td>SW54    </td><td>ASW0007sez </td><td>SDSSJ142620+561356 </td><td>1237659326017962463    216.5870    56.2323     </td><td>http://labs.spacewarps.org/spaghetti/model/CCZG2QBCV3  </td></tr>
<tr><td>SW55    </td><td>ASW0007t5y </td><td>SDSSJ142652.78+560001.3    </td><td>587733424408428946 216.7199    56.0004     </td><td>http://mite.physik.uzh.ch/data/008886  </td></tr>
<tr><td>SW55    </td><td>ASW0007t5y </td><td>SDSSJ142652.78+560001.3    </td><td>587733424408428946 216.7199    56.0004     </td><td>http://labs.spacewarps.org/spaghetti/model/G7O3HCHKYL  </td></tr>
<tr><td>SW4 </td><td>ASW0009cjs </td><td>SDSSJ142934.21+562541.0    </td><td>1237659326554964414    217.3925    56.4281     </td><td>http://mite.physik.uzh.ch/data/011763  </td></tr>
<tr><td>SW28    </td><td>ASW0007wfj </td><td>SDSSJ143055.96+572431.7    </td><td>1237655463776158102    217.7332    57.4088 ASW0007xrs  </td><td>http://mite.physik.uzh.ch/data/008758  </td></tr>
<tr><td>SW5 </td><td>ASW0007k4r </td><td>SDSSJ143454.47+522850.9    </td><td>1237661387069522357    218.7270    52.4808     </td><td>http://mite.physik.uzh.ch/data/012771  </td></tr>
<tr><td>SW6 </td><td>ASW0008swn </td><td>SDSSJ143628.00+563833.3    </td><td>1237655368759050812    219.1167    56.6426     </td><td>http://mite.physik.uzh.ch/data/012373  </td></tr>
<tr><td>SW58    </td><td>ASW0007h27 </td><td>SDSSJ143651.59+530706.0    </td><td>1237661388143198984    219.2150    53.1183 ASW0007iwp  </td><td>http://mite.physik.uzh.ch/data/008897  </td></tr>
<tr><td>SW29    </td><td>ASW0008qsm </td><td>SDSSJ143838+572647 </td><td>1237655369832727187    219.6589    57.4464     </td><td>http://labs.spacewarps.org/spaghetti/model/TQKS2E5S7H  </td></tr>
<tr><td>SW29    </td><td>ASW0008qsm </td><td>SDSSJ143838+572647 </td><td>1237655369832727187    219.6589    57.4464     </td><td>http://labs.spacewarps.org/spaghetti/model/2SU75GA4XN  </td></tr>
<tr><td>SW7 </td><td>ASW0007e08 </td><td>SDSSJ220256.82+023433.9   </td><td>1237678619552514623    330.7368    2.5761      </td><td>http://mite.physik.uzh.ch/data/007959  </td></tr>
<tr><td>SW42    </td><td>ASW00096rm </td><td>SDSSJ221716.58+015826.5    </td><td>1237678597005509292    334.3191    1.9740      </td><td>http://mite.physik.uzh.ch/data/011717  </td></tr>
</table>

**Comment by RafiKueng** [comment]
we have a first selection, make webpage with all for volunteers to inspect
